### ISSUE TITLE
Lightroom recipe doesn't seem to unlock by default

### ISSUE THREAD

**Issue by VortexParadox** [mortuusars/Exposure#109]
When I first installed this mod, I saw the new recipe toast for the camera, but nothing else. And after many days later after unlocking recipes for films there was nothing for the lightroom, I figured I was missing an ingredient but searching through the entries for the mod on CurseForge, Modrinth and even the Github Wiki, I found nothing about how to go around crafting one.
It wasn't until I finally caved in and installed JEI to search for the recipe. Since it was only asking for 4 planks of wood, a redstone torch and a lantern I figured there may be an issue with the recipe or some conflict, though nothing seems apparent and I don't have any of the mods listed in the "Known Issues" section.

Only warning I see on my logs is from the mod recommending create.

### MC Version:
1.20.1
### Mod loader and version:
Fabric 0.15.11
### Mod version:
1.7.4
### Log:
[21-7-24_mclog.log](https://github.com/user-attachments/files/16326296/21-7-24_mclog.log)

**Comment by mortuusars** [comment]
Lightroom recipe unlocks by obtaining a Developed Film Roll.
Camera recipe being unlocked from the start is not intended though. I'll fix it in the next version.
