### ISSUE TITLE
Photograph item leads to game crashed in 1.20.1 latest version

### ISSUE THREAD

**Issue by ChenM0M** [mortuusars/Exposure#111]
Minecraft Version: 1.20.1
Forge Version: Forge 47.3.5
Mod Version: Exposure 1.7.4
Log: https://mclo.gs/oDtTA7l

My game crashes when I take out a exposure:photograph in creative gamemode from the creative tab.
Exposure is the only mod in the modpack.
I found that the problem doesn't appear when I change the Exposure mod version to 1.7.2, It also leads to crash in 1.7.3.

**Comment by mortuusars** [comment]
Fixed in 1.7.5.
