### ISSUE TITLE
Placing Photographs (anywhere) causes an x-ray glitch.

### ISSUE THREAD

**Issue by NicksCraft2007** [mortuusars/Exposure#114]
When a photograph is placed on a block, you can see most entities, especially the armored mobs, quite clearly through blocks.
![Screenshot 2024-08-08 at 7 03 14 PM](https://github.com/user-attachments/assets/23e415ca-58b5-4a4a-af96-0b1ffb82f1ac)
![Screenshot 2024-08-08 at 7 04 14 PM](https://github.com/user-attachments/assets/5923380e-92dc-4731-96cf-3274047ccb9e)

**Comment by mortuusars** [comment]
Optifine is not supported. Use Sodium/Embeddium.
