### ISSUE TITLE
Curious mod developer question

### ISSUE THREAD

**Issue by BrickOyster** [mortuusars/Exposure#122]
Hello, I hope you are having a great day

I just saw the mod and am very intrigued, but I play 1.21.1 and want to try and port it
The problem is I have no clue where to start. I want to start by compiling the current working mod and then proceed with the port. Could you give me some guidance as to what libraries to install/ software to use for mod dev/build.

I am working on Visual Studio right now with a wsl linux as my working directory (subject to change is your wisdom sais I'm just wasting time)

Thank you kindly in advance for your time.

**Comment by mortuusars** [comment]
1.21 port is in progress.
If you have no clue where to start - you won't make port sooner than I am, most likely.

If you still want to try - I use IntelliJ IDE to develop. You'll also would need a JDK, but that might be handled by the IDE. If not - you'll need to install it manually.
MC 1.20.1 uses Java 17. 1.21 - Java 21.
I think that should be all you need to run a cloned project. 
But if you don't have experience with java, forge/fabric, architectury (Exposure is using it to support both mod loaders at once) - it would be pretty tough. And on top of that - my code is also not the best to understand and work with.

**Comment by BrickOyster** [comment]
Firstly thanks a lot for the response,
I eagerly await 1.21 port and will do more research/practice to maybe help in this or other projects

thanks for your time
