### ISSUE TITLE
Suggestion: Sepia film

### ISSUE THREAD

**Issue by V0idshock** [mortuusars/Exposure#13]
I suggested this in your discord, but i think it would be useful to have it here too.

The general idea is to make a sepia colored film, like the colored and the black and white. This effect can be approximated with a brown tinted glass as the camera's filter. The problem is that the resulting images are too colorful to be true sepia.

![Sepia](https://github.com/mortuusars/Exposure/assets/113664305/3bff361d-af8f-455e-91e6-857526df3da2)

**Comment by mortuusars** [comment]
As I understand, sepia effect was a result of adding sepia pigment when printing black and white photograph, so it wouldn't make much sence to have it as a film. 
I think it could be interesting to somehow produce sepia photos from black and white photos. When printing or after the fact.

**Comment by V0idshock** [comment]
That is a much better idea. Somebody also mentioned that Supplementaries has an antique ink, which makes maps sepia colored (treasure map style). There could be potential to have a compatability there, if you are into that sorta stuff.

**Comment by l3gacyb3ta** [comment]
I think that maybe colors could added that werent black and white or CMYK when developing. So instead of using a generated color pallete in the dither, you could alter it based on the inks present in the table!

**Comment by mortuusars** [comment]
Added in 1.4.0 in a form of Aged Photographs.
