### ISSUE TITLE
Exposure time

### ISSUE THREAD

**Issue by ruax2891** [mortuusars/Exposure#133]
Hey! I really like your mod, photography is one of my hobbies and being able to pursue it in one of my favorite games really fills my heart with joy and excitement.
I thought that adding custom exposure time to photos would be a nice addition, it lets you set the mood in photos and maybe catch details that you otherwise couldn't. It would also add a little bit of preproduction, you'd have to calculate the desired exposure time with a light meter. I don't know if this could be possible in current Minecraft, but if it is, it would be awesome!
Thank you for creating this mod.

**Comment by ruax2891** [comment]
Hey, I just realized the feature is implemented! Sorry for the extra issue. Last time I played this mod it wasn't there, that's my bad

**Comment by mortuusars** [comment]
Shutter speed was in the mod from the the release :)
