### ISSUE TITLE
Suggestion: Add images to books

### ISSUE THREAD

**Issue by RGBRedGreenBlue** [mortuusars/Exposure#15]
As the title hopefully says, I would like to be able to put a photo inside of a book and quill.

I don’t know how much effort this would take as I am no coder, and if it is too much effort that’s ok I just think it would be a cool idea for newspapers or scrapbooks etc.

If you do end up doing it could you please add compatibility for Let’s Do Candlelight’s note paper and typewriters.

**Comment by mortuusars** [comment]
Album is a planned feature, and should come in one of the future updates.

**Comment by RGBRedGreenBlue** [comment]
sorry for replying rather late, but is this the ability to put them in the existing books or a new item altogether?

if it is a new item can you add text?

**Comment by mortuusars** [comment]
Yes, there will be an ability to add some text under the photograph.

**Comment by mortuusars** [comment]
Added Album in 1.3.0.
