### ISSUE TITLE
Strange visual glitches with fluids when using Iris Shaders (1.19.2 Fabric)

### ISSUE THREAD

**Issue by TheTrueYak** [mortuusars/Exposure#21]
I'm running the 1.19.2 fabric version on quilt, and I've noticed that whenever a fluid is in view when using the camera with shaders enabled, fluids seem to float in the air nearby or just generally look weird and out of place. This happens with both water and lava, and I assume with modded fluids as well. I've attached some images below to showcase the glitches and how they only happen when using the camera. This is not quilt-only issue, as I also tested it on fabric with only exposure, sodium, indium, fabric api, forgeconfigapi, and iris, and the issue still persisted. This issue also seems to be shader-agnostic, as it happened with every shader I tested, those being complimentary shaders, complimentary unbound, silder's shaders, and BSL shaders. (I noticed that the clouds in silder's shaders were also affected by the same graphical glitch as fluids)

Versions:
exposure-1.19.2-1.2.0-fabric.jar
irismc1.19.2-1.6.11.jar

ComplementaryShaders_v4.3.3
ComplementaryUnbound_r5.0.1
Sildur's+Enhanced+Default+v1.131+Fancy
BSL_v7.1.04.1

fabric-api-0.76.0+1.19.2.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
indium-1.0.9+mc1.19.2
sodium-fabric-mc1.19.2-0.4.4+build.18

quilt-loader-0.22.0-1.19.2
fabric-loader-0.15.1-1.19.2

![2023-12-23_00 40 35](https://github.com/mortuusars/Exposure/assets/107325508/ef62aecc-2877-4b89-a6f4-255bd83d3275)
![2023-12-23_00 40 43](https://github.com/mortuusars/Exposure/assets/107325508/dbbabd20-13e2-4693-b9e1-5f2e48311e42)
![2023-12-23_00 40 48](https://github.com/mortuusars/Exposure/assets/107325508/85ac1002-8038-4571-b488-90942b6a9545)
![2023-12-23_00 42 57](https://github.com/mortuusars/Exposure/assets/107325508/8444efe3-716b-46e0-a5ed-208ddd628707)
![2023-12-23_01 03 16](https://github.com/mortuusars/Exposure/assets/107325508/6a985220-f5b8-4a8b-b1f7-89d161787d50)

**Comment by mortuusars** [comment]
That's a weird issue. It's tied to the viewfinder overlay somehow. And because overlay is hidden when the image is taken - photos look normal. 
I'll look into it.
