### ISSUE TITLE
crashes players when taking a picture on servers

### ISSUE THREAD

**Issue by GlaedrLudos** [mortuusars/Exposure#24]
im working on a vanilla+ type modpack, and i really wanted to add the exposure mod. but everytime one of us tries to take a photo, everyone but the one taking the picture is kicked from the server and given a very long message. i cant tell if its due to conflicts with another mod, or something else. but if theres any specific info you need, just let me know and i'll do my best to provide it.

**Comment by mortuusars** [comment]
Does the closed issue means that it is resolved?

**Comment by Neakita** [comment]
This is happening on my server. Do you need logs or something else?

**Comment by KatterMaw** [comment]
Disconected player message:
https://cdn.discordapp.com/attachments/548112315929722881/1191101568066535424/image.png?ex=65a436c7&is=6591c1c7&hm=9474713a6b7fee1af6527d6d25f51c0ec1281cbc5ba4f162dd973a6c88fe224e&

**Comment by Neakita** [comment]
![image](https://github.com/mortuusars/Exposure/assets/68691636/b6bb7cd0-27ce-4ef0-b0bc-b1d949b1485b)
Disconnected player's message

**Comment by GlaedrLudos** [comment]
> Does the closed issue means that it is resolved?

The issue we ran into was due to C2ME which was a separate mod. It’s in alpha and was causing the crashes so we had to remove it. But Exposure was fine once C2ME was removed

**Comment by GlaedrLudos** [comment]
> ![image](https://private-user-images.githubusercontent.com/68691636/293520566-b6bb7cd0-27ce-4ef0-b0bc-b1d949b1485b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNTE1NjMsIm5iZiI6MTcwNDA1MTI2MywicGF0aCI6Ii82ODY5MTYzNi8yOTM1MjA1NjYtYjZiYjdjZDAtMjdjZS00ZWYwLWIwYmMtYjFkOTQ5YjE0ODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE5MzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NGJmYmI3MzAzMjcwODA1MGQxODYzNjdjN2MwNDkyZDQwYWIxY2M2MGM2NzVjMzM2Y2IxNDIwOTViOWY2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GGrZE-OUDq_Cbewh4JcCaaul-VHEnoReXBpJjnAH3wc) Disconnected player's message

Remove C2ME and the issue should be resolved. However we have noticed Exposure causes zoom mods such as WI Zoom to bug some. Not to the point of unplayability, but just more of an irritation. We remedied this by switching from WI Zoom, to the better Spyglass mod

**Comment by mortuusars** [comment]
>  Exposure causes zoom mods such as WI Zoom to bug some. Not to the point of unplayability, but just more of an irritation. We remedied this by switching from WI Zoom, to the better Spyglass mod

This was already reported and will be fixed in a new version.

**Comment by mortuusars** [comment]
@KatterMaw 
Please provide the full log.

**Comment by Neakita** [comment]
[2024-01-01-1.log](https://github.com/mortuusars/Exposure/files/13804090/2024-01-01-1.log)
Here is

**Comment by mortuusars** [comment]
I've tried to adjust some things to fix the issue, but I cannot test it because I cannot replicate the crash.
If someone wants to test it - I can upload a version with the fixes to github.

**Comment by Neakita** [comment]
> I've tried to adjust some things to fix the issue, but I cannot test it because I cannot replicate the crash. If someone wants to test it - I can upload a version with the fixes to github.

I will test it with my friend as soon as we have the opportunity.

**Comment by mortuusars** [comment]
@KatterMaw I have released a new version on modrinth/cf with possible fix.

**Comment by Neakita** [comment]
@mortuusars seems to be working now https://www.youtube.com/watch?v=YgpmBEP5Ixc
