### ISSUE TITLE
In some cases, replacing film in the lightroom may result in inability to operate

### ISSUE THREAD

**Issue by IwasConfused** [mortuusars/Exposure#27]
When using a film with fewer frames to replace a film with more frames in lightroom, it will result in the inability to view and select frames.
![nope](https://github.com/mortuusars/Exposure/assets/70762136/593a87c0-5daf-4f5a-aca3-f81cc704cafd)

How to reproduce：
1. Prepare a film with more frames (film A) and another film with fewer frames (film B).
2. Put film A into the lightroom and roll it to the frame that exceeds the frames number of film B.
3. Take out film A and put film B into the lightroom, now it cannot be operated.

**Comment by mortuusars** [comment]
In the meantime while I'm fixing this - pressing A/D or Left Arrow/Right Arrow on keyboard will refresh the display and it will start working normally again.
