### ISSUE TITLE
Game crashes upon launch (Fabric 1.20.1)

### ISSUE THREAD

**Issue by Phil-Miles** [mortuusars/Exposure#33]
Without the Fabric API, the log clearly says I need one.

I have downloaded Fabric for 1.20.1 version and now the game crashes due to 'unknown error' on startup.

**Comment by mortuusars** [comment]
Please send the crash log.

**Comment by Phil-Miles** [comment]
Here it is:
[crash report.txt](https://github.com/mortuusars/Exposure/files/13889997/crash.report.txt)

**Comment by mortuusars** [comment]
Exposure requires `Forge Config Api Port` mod to work.
