### ISSUE TITLE
Crash at launch on Fabric 1.20.4

### ISSUE THREAD

**Issue by bigjazzfan** [mortuusars/Exposure#34]
[crash-2024-01-13_14.46.13-client.txt](https://github.com/mortuusars/Exposure/files/13929758/crash-2024-01-13_14.46.13-client.txt)

As the title says, crash report attached

**Comment by mortuusars** [comment]
Though the error here is due to the `Forge Config Api Port` missing (it's a required dependency), I doubt it will run on 1.20.4. 
Exposure only supports 1.19.2 and 1.20.1.
