### ISSUE TITLE
The second layer of the head does not tilt when looking through the viewfinder

### ISSUE THREAD

**Issue by linkarvane** [mortuusars/Exposure#40]
Holding the camera:
![A screenshot of a player holding the camera](https://github.com/mortuusars/Exposure/assets/86122120/a2d22bca-964e-4bad-bea2-c237d36679d9)
Looking through the viewfinder:
![A screenshot of a player looking through the viewfinder](https://github.com/mortuusars/Exposure/assets/86122120/accd719a-a242-4073-9811-72f2a66fd411)
As you can see, the second layer stays in the same position

Also it seems that the issue is only present in the Fabric version

**Comment by mortuusars** [comment]
I have made changes to potentially fix this in 1.3.0, but I cannot test it myself. 
Please let me know if this is fixed it or not.

**Comment by linkarvane** [comment]
Yes, it's fixed
