### ISSUE TITLE
Copying black and white photo recipe

### ISSUE THREAD

**Issue by Tefnya** [mortuusars/Exposure#42]
Basically, in jei i saw a recipe by ID: copying_black_and_white_photograph, but it seems it was never used.
Right now black and white photos use colored photograph **copying recipe** and **description without jei**.
So we probably should either scrap this recipe or put it to use if it was an oversight.

**Comment by mortuusars** [comment]
I forgot to change "FilmType" to just "Type" in the recipe after I changed it in code. Would be fixed in next version.
If you want it fixed faster - change this recipe through a datapack or something to have it match the correct name: "Type".

```json
{
  "type": "exposure:photograph_copying",
  "photograph": {
    "type": "forge:partial_nbt",
    "item": "exposure:photograph",
    "nbt": "{Type:\"black_and_white\"}"
  },
  "ingredients": [
    {
      "tag": "exposure:photo_papers"
    },
    {
      "tag": "exposure:black_printing_dyes"
    }
  ],
  "result": {
    "item": "exposure:photograph"
  }
}
```
