### ISSUE TITLE
Crash when holding shift

### ISSUE THREAD

**Issue by flimblet** [mortuusars/Exposure#46]
Always when I got the camera equipped, if I press shift, the game freezes, and then crashes.

Crash log:

[crash-2024-02-14_18.01.24-client.txt](https://github.com/mortuusars/Exposure/files/14288554/crash-2024-02-14_18.01.24-client.txt)

**Comment by mortuusars** [comment]
Duplicate of https://github.com/mortuusars/Exposure/issues/19
