### ISSUE TITLE
Lights up! is almost unachievable

### ISSUE THREAD

**Issue by Tefnya** [mortuusars/Exposure#5]
Out of ~100 attempts got it only 3 times and it was kinda random. When tried from same position and looking the same direction it didn't work. My guess is because flash brings the light level around the player up to 14 and achievement fails the "darkness check". Or could be something else.

**Comment by mortuusars** [comment]
Yeah, you're right. It checks after the flash is applied which fails the check. Will be fixed in next version.

**Comment by mortuusars** [comment]
Fixed in release version.
