### ISSUE TITLE
Larger Films & Photo Stacks (enhancement)

### ISSUE THREAD

**Issue by stalkernaut** [mortuusars/Exposure#50]
I've messed around quite a bit and even got a way to make video with the photo stacks but due to the limited film & photo stack sizes its hard to get much farther with them, there are probably some size limitations but bigger photo stacks would be nice for video & general storage, it could be a config or maybe a special photo storage thing that you have to craft but it would be very convenient,
for larger film sizes you could have to craft them like 2 16 frame films and 1 diamond to get a 32 frame film, and 2 32 frame films and 1 emerald to make a 64 frame film, or maybe in place of diamonds and emeralds there could be a film extender item
I know its a lot to ask but i hope it gets added!

**Comment by mortuusars** [comment]
You can achieve this by specifying `FrameCount` and `FrameSize` tags in film nbt. Adding a recipe for an item like this is not hard.

But you should be careful increasing count too much. Frames store additional data about the shot, too many of them can cause the item size to go above the network packet limit. I have not tested what this limit is exactly.

**Comment by stalkernaut** [comment]
> You can achieve this by specifying `FrameCount` and `FrameSize` tags in film nbt.

Can the same be done for custom photo stack sizes (like a special nbt value for max size) or is that hard coded?

**Comment by mortuusars** [comment]
No, it's hardcoded to 16.
I'll think about making it configurable in the next update.

**Comment by mortuusars** [comment]
Added config option in 1.4.0.
