### ISSUE TITLE
(Forge 1.19.2) Exposure causing a startup crash when JEI is installed

### ISSUE THREAD

**Issue by OhDuffo** [mortuusars/Exposure#51]
I tried adding this mod to my modlist on Forge 1.19.2, and it seems to cause JEI to crash.
Crash Report:
[PasteBin](https://pastebin.com/TwT4AE8L)

**Comment by OhDuffo** [comment]
Updating JEI to the most recent version did not work, and neither did removing OptiFine.

**Comment by mortuusars** [comment]
You have an outdated Create version (0.5.0). 
Exposure adds a compat to allow developing film with spouts, and it will probably only work with 0.5.1+.

**Comment by OhDuffo** [comment]
That seemed to work! Thank you so much!
