### ISSUE TITLE
Oh no, a visual bug?

### ISSUE THREAD

**Issue by Bksp** [mortuusars/Exposure#56]
When putting 2 photographs on a wall, they overlap the render, making this a very noticeable problem.
![image](https://github.com/mortuusars/Exposure/assets/47306658/6e875dc9-b8fc-48ca-abd1-598a80f25985)

**Comment by mortuusars** [comment]
Does it happen with no shaders or different shaders?

**Comment by Bksp** [comment]
![2024-02-27_14 45 18](https://github.com/mortuusars/Exposure/assets/47306658/9cb9f007-bf50-4a45-ad11-5e9ee4f19888)
Yep

**Comment by mortuusars** [comment]
Judging by the grass, I'm guessing you're using Optifine?

**Comment by Bksp** [comment]
yep o:

**Comment by mortuusars** [comment]
Optifine is not supported. It's closed source and known for causing issues with other mods.
You can use Sodium/Embeddium and Iris/Oculus for shaders instead.
