### ISSUE TITLE
Any plan for a fabric port?

### ISSUE THREAD

**Issue by VulpesStella** [mortuusars/Exposure#6]
Hello! I wonder if you have any plan for a fabric port? If not, can I make my own port? Thank you!

**Comment by mortuusars** [comment]
I plan to do a Fabric port. But the MIT licence is not forbidding you to port it yourself.
If you plan to port it - It would be nice if you credited me as an original author and with a rewards split of like 50% on Curseforge/Modrinth.

**Comment by lostopkk** [comment]
> I plan to do a Fabric port. But the MIT licence is not forbidding you to port it yourself. If you plan to port it - It would be nice if you credited me as an original author and with a rewards split of like 50% on Curseforge/Modrinth.

Thank you very much for the fabric port, I hope to have more mods for this modloader! This mod is incredible and deserves recognition!
