### ISSUE TITLE
Suggestion: Ability to save photos taken to your device as an image file

### ISSUE THREAD

**Issue by Paxilmaniac** [mortuusars/Exposure#61]
I'd like to be able to save some of the photos I take using this mod to my device locally to my device, and as far as I am aware there is no way to do this without placing the photos and taking screenshots of them.

**Comment by mortuusars** [comment]
Exposures are saved to `<instance>/exposures/<world>` folder when viewed (photograph screen is opened).
You can also use `/exposure export` command to export as pngs, but it's serverside - if you playing on remote server it will save them to server folder. For singleplayer it would be on your PC of course.

**Comment by Paxilmaniac** [comment]
That answers my question then, perfect.
