### ISSUE TITLE
Album Crash

### ISSUE THREAD

**Issue by DrCookie95** [mortuusars/Exposure#62]
Trying to open an empty album still crashes my game

**Comment by mortuusars** [comment]
Please provide a crash report.

**Comment by chrisilly** [comment]
I'm having the same issue. It's not giving me a crash report though. The game freezes and stops responding. The only thing I get is this: 

Process crashed with exitcode -805306369.

My modlist is quite extensive. It could be anything as far as I can tell 🤷

**Comment by mortuusars** [comment]
@culliiing Do you have REI, REI plugin Compatibilities and FTB Teams installed?

**Comment by chrisilly** [comment]
@mortuusars I don't have FTB Teams, but yes I have REI and REI plugin compatibilities. Thanks for fixing the issue and great work on these fantastic mods!!
