### ISSUE TITLE
Visual issue with cold sweat

### ISSUE THREAD

**Issue by Giubbottoman** [mortuusars/Exposure#63]
Hi, I got an issue with "Exposure" mod when paired with "Cold Sweat" mod (link: https://www.curseforge.com/minecraft/mc-mods/cold-sweat). Since version 1.4.0 every time I close the camera, whether I take a picture or not, it turns on the "Cold Sweat" shader that signals too hot temperatures. This happens even if the Temperature should be cold, so its not a triggering factor. The visual Issue resets only when I quit to title and re-open the world, not when I die or put myself in a situation where the shader should ususally trigger.
Anyway, good job with the mod, I'm loving it.

**Comment by mortuusars** [comment]
I cannot reproduce it. MC 1.20.1, Cold Sweat 2.3-b02a, Exposure 1.4.0. All seem to work fine, even with filters.
Tried with Embeddium and Oculus installed - also fine. With shaders - also fine.

This may be a conflict with other mod. You can remove mods in portions until the issue goes away. This can help narrow down the problem.

**Comment by Giubbottoman** [comment]
I'll try doing it and report anything I can find.

**Comment by Giubbottoman** [comment]
I found out how it happened, It's a bit of an extreme situation: you should be in survival, have recently triggered the heat shader (easier solution would be going to the nether) and only then use the camera. Once closed the shader will be permanently applied. It doesn't matter how long you wait after the heat shader disappeared in the first occasion: I tried waiting for the heat effect to vanish but the next time i opened and closed the camera it gave the same result. Also, just to make sure that you get to emulate the same situation, you should firstly remove the grace effect (It prevents you from receiving any consequence from temperature), secondly wait for the shader that makes you see round pixels (the heat causes the player's view to bob before the shader is applied.) 
P.S. I call the effect "shader" but I actually don't know what it is, so sorry if I misspelled it.

**Comment by Giubbottoman** [comment]
Sorry, I almost forgot to try reproducing this in a modpack that contains no other mods and when I did nothing happened.
Tomorrow I'll try adding mod by mod and tell you wich mod caused this. 
Sorry if I opened an issue without exploring it that much.

**Comment by mortuusars** [comment]
Ok, I seem to have replicated the issue. For me it only happens with a filter (glass pane) installed. Otherwise it works fine.
And after it happens (blur is applied after exiting viewfinder), removing filter and opening viewfinder again seems to fix the issue and clears the blur.

It's a bit tricky to fix, but I think I can do something about it.
If another mod (besides exposure and cold sweat) complicates things further please let me know.

**Comment by mortuusars** [comment]
Another cool way to remove the shader is to open F3+F4 gamemode changing menu, but selecting current gamemode again instead of changing it. It would only work with cheats enabled though. And at this point you could just use `/shader remove @s` command.

**Comment by Giubbottoman** [comment]
The Issue was indeed the glass pane, I tried with a few other mods that might influence the player's view (Embeddium, spark, ferritecore, embeddium++, mudernfix, fusion, fastload, Entity culling fabric/forge) but none of them actually made any difference.
