### ISSUE TITLE
Exposure crashing in combination with spout from the create mod

### ISSUE THREAD

**Issue by Redmike7** [mortuusars/Exposure#64]
Basically the game crashes few seconds after you place Spout from create mod into the world.

Minecraft launcher error message - Error: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.content.fluids.spout.FillingBySpout failed

Game version - 1.20.1
Modloader - Fabric
Fabric version - 0.15.7
Exposure version - exposure-1.20.1-1.4.0-fabric
Create version - create-fabric-0.5.1-f-build.1335+mc1.20.1

Slight update - I think it might have something to do with the integration between these mods as there is and option in create config to turn on/off developing images with spout. Turning it off does not fix the crash issue.

**Comment by pobab** [comment]
i can confirm it! i have same issue, here is my report

this is crash log on my server: https://mclo.gs/ZBDFgai#L5
here is crash log on my client when trying in single player:  https://mclo.gs/wyNPD4i

hope it will help this issue

**Comment by mortuusars** [comment]
Fixed in 1.4.1
