### ISSUE TITLE
quilt compatibility issue

### ISSUE THREAD

**Issue by sandros94** [mortuusars/Exposure#65]
on the Modrinth page Exposure is listed as compatible with quilt `1.20.1`, while `Forge Config Api Port` actually isn't compatible with that version.

Should this be noted somewhere?

Forcing a `Forge Config Api Port` install mostly works (only thing I've noticed so far is the craft recipe for the camera missing).

**Comment by mortuusars** [comment]
I don't seem to have the issues you're mentioning.
Just now I have created fresh instance of quilt 0.24.0 - 1.20.1 using Prism Launcher. Downloaded Exposure, Quilted Fabric API, JEI, Forge Config Api Port from Modrinth using Prism's mod browser. It didn't show me that Forge Config Api Port isn't compatible. All works fine. Every recipe is there.

**Comment by sandros94** [comment]
After talking a bit with Fuzs on discord about `Forge Config Api Port` he double confirmed that it should be compatible with Quilt, but since he doesn't have proper testing he preferred to not tag it. This causes Modrinth launcher to not auto-install `Forge Config Api Port` as a dep when installing Exposure, requiring it to be done manually.

While, on the other hand, the recipe issue was caused by other factors, mainly involving how I was appending mods to the server container deployment and stale caches. Now everything works perfectly, thanks for this amazing mod!
