### ISSUE TITLE
Client crash when picture is in inventory

### ISSUE THREAD

**Issue by brodyofhearts** [mortuusars/Exposure#69]
I was trying to print off a picture from a coloured film in a multiplayer server. Once the image was created, my game would instantly crash and my screen would go black and unresponsive upon logging back into the server. Breaking the block, picking up the picture, and opening my inventory produced the exact same issue.

I am running Forge 1.19.2.

[crash-2024-03-19_00.30.59-client.txt](https://github.com/mortuusars/Exposure/files/14644998/crash-2024-03-19_00.30.59-client.txt)

**Comment by mortuusars** [comment]
Does it happen with only Exposure installed? Does it happen with same mods but in singleplayer?

**Comment by brodyofhearts** [comment]
I revised the modpack for other reasons and I ended up removing and reinstalling the exposure jar file. That has seemingly fixed it, both with singleplayer and multiplayer. I'm not sure if it was a mod I removed that was incompatible or if the jar file or the server files were just faulty.
