### ISSUE TITLE
Additional info about how to use /exposure load

### ISSUE THREAD

**Issue by AlephZero1** [mortuusars/Exposure#74]
Hi! Is it possible to create a photograph with your custom PNG on it and place it on a wall?  If I want to make a gallery with my custom pics without messing with resoursepacks and paintings, for example.
I tried this: 
/exposure load 1500 "D:/Games/Mojang Minecraft/exposures/The 11-3-1 room world/custom.png" 100 
And it didn't work. Console advices me to see logs, but I don't know where to look for them.

**Comment by mortuusars** [comment]
It's possible. 
Current log is written in <instance>/logs/latest.log file.

**Comment by Pholith** [comment]
I just made it work with the following commands, it works really well.
```
/exposure load withDithering 256 "D:/Images/MyImage.png" 5
/give Pholith exposure:photograph{Id:"5"}
``` 

You can also preview the loaded image with
```
/exposure show latest
```

**Comment by mortuusars** [comment]
Closing the issue due to inactivity.

If you are still having problems with it, make sure all values are correct (read wiki for details). Encase path in quotes. Check slashes in the path (use '/' or '\\'). And don't forget to specify an ID after the path.
