### ISSUE TITLE
Not leaving lightroom during chromatic printing makes photo white (relogging fixes it) 

### ISSUE THREAD

**Issue by Tefnya** [mortuusars/Exposure#76]
When using chromatic sheet in the lightroom the final time and not leaving lightroom gui throughout the process, the photograph will be completely white and will be displayed everywhere as blank. After relogging the intended picture appears.

-Exposure 1.5.0, forge 1.20.1

**Comment by mortuusars** [comment]
Fixed in 1.5.1.
