### ISSUE TITLE
Developing color film requires potions?

### ISSUE THREAD

**Issue by wackydumbidiot** [mortuusars/Exposure#79]
Forge 1.20.1 - Mod Version 1.5.1 -  I'm unsure whether this is intended or not, but the crafting recipe for getting a colored film developed requires an akward potion, mundane potion and a thick potion instead of water bottles. This was pretty strange when I first encountered it. If this is intentional then it's cool but I just think it's kind of a strange design.

**Comment by mortuusars** [comment]
It's intended. If anything, developing black and white with water is strange, but this was done for balance reasons.
Only issue I see with these three potions is that they look the same, and this sometimes may confuse players.
