### ISSUE TITLE
Concept: Liquid Developer

### ISSUE THREAD

**Issue by vivvyinks** [mortuusars/Exposure#8]
The ability to combine the three separate potions required for color development into one "color developer" fluid would be useful, so you can use one bottle instead of three. The same amount of work would be required (brewing the three separate potions), but you could potentially automate mixing the fluids together with the Create mod (or another mod that supports fluid mixing), and you'd be dealing with less bottles overall. Potentially, developer could even stack.

**Comment by mortuusars** [comment]
I think this shouldn't be too hard to do with KubeJS/CraftTweaker, so adding this to the mod just for it to have single purpose is not really justifiable.
