### ISSUE TITLE
Suggestion: File Management

### ISSUE THREAD

**Issue by GJdude** [mortuusars/Exposure#80]
It seems that every photo ever taken, including ones that are destroyed or deleted in the creative inventory afterwards, creates files in the world file. Whilst small, over time these could pile up to pretty huge amounts, so it might be nice to have an easier way to go through them and delete ones that you don't need any more.
In a server where the camera's being used a lot, this could save up a fair amount of clutter and some space too. It's very hard to tell which one is which when they're just a jumble of numbers, and loading them up ingame one at a time is very slow.

**Comment by mortuusars** [comment]
I've made an addon that can help manage stored exposures:
https://www.curseforge.com/minecraft/mc-mods/exposure-catalog
https://modrinth.com/mod/exposure-catalog
