### ISSUE TITLE
Suggestion: Shutter speed can cause smears

### ISSUE THREAD

**Issue by limelier** [mortuusars/Exposure#86]
It's really cool that you can change the shutter speed on the camera. One suggestion I'd add, though, is to also add a control for the ISO, and let slower shutter speeds capture information more than once, blending it together. This way, one can use longer shutter speeds to get smear-y images of things in motion.

**Comment by mortuusars** [comment]
Although having motion blur on long shutter speeds would be cool and expected effect, it, most likely, will not be added. 
It's not a trivial thing to implement. And, in terms of gameplay, I'm not sure that it's worth the effort, to be honest.
I'm open to contributions, though. If someone knowledgeable is willing to code it.

ISO control for film is not really logical. Films have fixed ISO value.

**Comment by limelier** [comment]
fair enough, thanks for the explanations 👍
