### ISSUE TITLE
Suggestion: Black and White Pictures can be colored (?)

### ISSUE THREAD

**Issue by Tri-Iris** [mortuusars/Exposure#88]
I am not sure how to explain this feature well, and it might be a bit more complicated

When you take a black and white photo, you could then add color to it via a new block that takes the specific value or the crafting table. 
So the black and white photo will turn this.
![2024-05-04_10 15 52](https://github.com/mortuusars/Exposure/assets/143235935/9bbab31a-89ef-4f42-98db-a03db77ec5ac)
Into this
![2024-05-04_10 15 52](https://github.com/mortuusars/Exposure/assets/143235935/3730dbc8-3220-4ef3-b578-3d00012b9526)
I'm not sure how you could do specific colors for specific value, but it can be seperated from light vs. shadow. I used gradient maps to do this. 
So it would look like these.
![2024-05-04_10 15 52 (1)](https://github.com/mortuusars/Exposure/assets/143235935/e28f15a0-5bdc-4de8-bdb0-315f4dd20d9f)
![2024-05-04_10 15 52 (2)](https://github.com/mortuusars/Exposure/assets/143235935/f2a5ef72-76b0-4d86-904e-d1decf062e82)

**Comment by mortuusars** [comment]
Dedicated coloring feature is not planned currently.
But using Chromatic process you can get interesting colors for BW images. 
This is what I've got while playing around with it a bit:
![Player459_chromatic_2201785](https://github.com/mortuusars/Exposure/assets/65141267/0730cbe1-fc2e-48e7-8d24-9e1b3ebf0c3f)
![Player446_chromatic_2202730](https://github.com/mortuusars/Exposure/assets/65141267/4a7c2ff0-636d-474b-9842-e7e6643953d4)
![Player446_chromatic_2199642](https://github.com/mortuusars/Exposure/assets/65141267/9149a1ff-2ee5-40f0-be88-8473b4cca116)
![Player446_chromatic_2198614](https://github.com/mortuusars/Exposure/assets/65141267/a4105934-9cb6-4c4f-8111-ddeba7b584ed)
![Player446_chromatic_2191070](https://github.com/mortuusars/Exposure/assets/65141267/005c7dda-b183-47ba-b9a8-92d4f79274df)
![Player446_chromatic_2188013](https://github.com/mortuusars/Exposure/assets/65141267/8ae0dcb1-9ffb-436d-90b7-9d28bdcb4b16)
![Player446_chromatic_2205418](https://github.com/mortuusars/Exposure/assets/65141267/74d28e43-e176-442c-848f-7bde1cb77818)

Also you can make Chromatic images warmer/cooler by using different shutter speeds for specific channels.

**Comment by Tri-Iris** [comment]
I've been trying to figure out how to do chromatic filters, but the wiki is a bit vague in it.. heh....

**Comment by mortuusars** [comment]
It's meant to be vague. I intended this feature to be somewhat hidden and some kind of a reward for curious players and for those how know about trichrome process. Probably shouldn't have put it in the wiki at all lol.

**Comment by Tri-Iris** [comment]
i see. well, time to see if i can find it!!1!!
