### ISSUE TITLE
Unable to Print the Picture 

### ISSUE THREAD

**Issue by AMN-D** [mortuusars/Exposure#89]
![image](https://github.com/mortuusars/Exposure/assets/129135638/0a929773-bc55-4ab4-af5e-e14b3f72ff13)

Please Help me i really like this mod. I want to print the picture but when i try to put in the film it just wont go in the slot no matter what i do , even tried shiftClick . 

am i doing something wrong ?

**Comment by mortuusars** [comment]
Film should be developed first. You're trying to insert undeveloped film roll.
