### ISSUE TITLE
Chromatic process only prints red channel

### ISSUE THREAD

**Issue by Anikyte** [mortuusars/Exposure#92]
When in the lightroom, I can only print the red channel, even when the photo clearly was taken with a green lense. Can't figure out how to change this. It prints red no matter what colour lense was used. 
![Screenshot_20240608_005912](https://github.com/mortuusars/Exposure/assets/48958412/542ceca7-39f9-4261-b39d-a29d0e1418ac)
1.20.1
47.3.0
1.6.0

**Comment by mortuusars** [comment]
It prints channels in order. Red always would be first on the paper.
Channel you see on the frame tooltip is just a reminder to you to choose correct frame to print. You can print them in any order.

Also, you can get interesting effects when printing out of order.
