### ISSUE TITLE
suggestion: compatibility with controller mods such as "controllable"

### ISSUE THREAD

**Issue by KaibuKing** [mortuusars/Exposure#94]
hi there sorry for accidentally pressing send too early and not writing a description, but i just wanted to suggest a compatibility with controller mods such as controllable. RIght now, there's no way to zoom in with both mods. its ok if you don't want to tho :)

**Comment by mortuusars** [comment]
I don't have a controller so I cannot test how it works, but Controllable has to have a way to bind Wheel Up/Down to a controller input.
