### ISSUE TITLE
ticking block entity issue on server [Forge]

### ISSUE THREAD

**Issue by Atlas-Maker** [mortuusars/Exposure#97]
Trying to finish printing a chromatic picture while on a server crashes the server 

[crash-2024-07-02_12.00.54-server.txt](https://github.com/user-attachments/files/16071898/crash-2024-07-02_12.00.54-server.txt)
[latest.log](https://github.com/user-attachments/files/16071903/latest.log)

**Comment by mortuusars** [comment]
Fixed in 1.7.2
